version: '3.1'
services:
#  server: TODO:
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "go_restful_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postres"]
      interval: 10s
      timeout: 5s
      retries: 5