### Successful test: check response status is 200
GET http://localhost:8080

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 200");
});
%}